### PR TITLE
Update for changes on DownloadFile.ps1 logic

### PR DESCRIPTION
**Pull request by Arthurvdv**
The logic of the DownloadFile.ps1 on https://github.com/StefanMaron/vsc-lintercop/blob/master/DownloadFile.ps1 has been updated today. There's a small change required to make the example working again.

@StefanMaron was a great help on this, thank you!

### CODE REVIEW

**Comment by Arthurvdv** [comment]
@NAVFreak, no the changes are in the LinterCop filename area. I'll try to explain a bit more here.

There are two changes necessary to have it working again.

A) Completely remove this line
```powershell
$BCLinterCopFileName = "BusinessCentral.LinterCop.dll"
``` 
B) Remove the '$BCLinterCopFileName' property (and backslash) from the last line to this:
```yaml
& $env:AGENT_BUILDDIRECTORY\$FileName $env:BUILD_SOURCESDIRECTORY $false

```

The result should look like this

```yaml
steps:
- task: PowerShell@2
  displayName: 'Download BusinessCentral.LinterCop.dll'
  inputs:
    targetType: 'inline'
    script: |
      $FileName = "DownloadFile.ps1"
      $GitHubUri = "https://raw.githubusercontent.com/StefanMaron/vsc-lintercop/master/$FileName"

      try
      {
          Write-Host "Downloading PowerShell script $GitHubFileName from $GitHubUri..." -ForegroundColor Yellow
          Invoke-WebRequest -Uri $GitHubUri -OutFile $env:AGENT_BUILDDIRECTORY\$FileName
      } 
      catch [System.Net.WebException] 
      {
          Write-Host "Error connecting to $GitHubUri. Please check your file name or repo name and try again." -ForegroundColor Red
      }

      Write-Host "Success. Now executing $FileName" -ForegroundColor Green

      & $env:AGENT_BUILDDIRECTORY\$FileName $env:BUILD_SOURCESDIRECTORY $false
```

**Comment by NAVFreak** [comment]
It works! 🎉🥳
Thank  you so much for the quick response!

**Comment by waldo1001** [comment]
Thank you so much!!

**Review by waldo1001 — APPROVED** [review]

**Comment by waldo1001** [comment]
Big thanks, Arthur.

**Pull request merged**
